# Whether to ask user about dangerous actions or not
zksync_action="dont_ask"

# Miscellaneous options for different infrastructure elements
[misc]
# Download setup files from SETUP_NETWORK_DIR if PROVER_DOWNLOAD_SETUP=1 or use local files if PROVER_DOWNLOAD_SETUP=0
prover_download_setup=false
# Network location of setup files
prover_setup_network_dir="-"

# Used to configure env for docker
docker_dummy_prover=false


# API key for the analytics script
etherscan_api_key="unset"

# Configuration for the fee seller script
max_liquidation_fee_percent=5
# fee_account_private_key is set in `private.toml`

reserve_fee_accumulator_address="unset"

established_assets_for_withdrawing_through_zksync="ETH,DAI,USDC"

# Format of logs in stdout could be "plain" for development purposes and "json" for production
log_format="plain"

sentry_url="unset"
